# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: 50

development:
  <<: *default
  database: libDB


test:
  <<: *default
  database: libDB

production:
  <<: *default
  database: libDB
